#!/bin/bash
read -p "please enter file name: " fnam
read -p "please enter test number: " num

echo Line: 
wc -l $fnam
echo Characters: 
tail -1 $fnam | wc -c

chmod u+x $fnam
git add .
git commit -m $fnam$num
git push
